export const TWITCH_CONFIG = "twitchConfig"; // CAI processing
export const TWITCH_CUSTOM_REDEEMS = "twitchRedeems";
export const TWITCH_AUTH_CB = "twitchAuthCb";
export const TWITCH_AUTH = "twitchAuth";
export const TWITCH_SELECTED_REDEEM_CHANGE = "twitchSelectedRedeemChange";
export const TWITCH_REDEEM = "twitchRedeem";
export const TWITCH_MESSAGE = "twitchMessage";
export const TWITCH_IRC_STATUS = "twitchIrcStatus";
export const TWITCH_PUB_SUB_STATUS = "twitchPubSubStatus";
