on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: npm install, build, and test
        run: |
          cd ./CharaTwitch.App
          npm install
          npm run build

      - name: Copy over react build
        run: cp -r ./CharaTwitch.App/build/ ./CharaTwitch.App/public

      - name: Get current version
        id: version
        run: echo "::set-output name=version::$(jq -r .version package.json)"

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ steps.version.outputs.version }}
