on:
  push:
    branches: ["Electron"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest]
        node-version: [20.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change to App Directory
        run: cd ./CharaTwitch.App

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npx electron-forge make --platform=win32

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-artifacts
          path: /CharaTwitch.App/out/
