on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build-nw
        
    - name: Get current version
      id: version
      run: echo "::set-output name=version::$(jq -r .version package.json)"

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: ./dist/src

    - name: Create Git Tag
      run: |
        # Create a tag name based on the commit hash
        TAG_NAME="${{ steps.version.outputs.version }}"

        # Create the tag
        git tag $TAG_NAME

        # Push the tag to the repository
        git push origin $TAG_NAME

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "$GITHUB_WORKSPACE/node-app"
        body: "release"
        tag: ${{ steps.version.outputs.version }}
